#!/bin/sh

set -e

case "$1" in
    configure)
        if ! getent passwd _dnscrypt-proxy >/dev/null; then
            adduser --quiet --system --no-create-home --force-badname \
                    --home /run/dnscrypt-proxy _dnscrypt-proxy
        fi
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
